package dataframes

import java.util.UUID

/**
  * Created by amoussi on 17/10/18.
  */
case class  AudiencePoi(id: String,
                        pyear: String,
                        pmonth: String,
                        pday: String,
                        pdate: java.sql.Timestamp,
                        poi_id: String,
                        terminal: String,
                        uad_terminal: String,
                        bot: String,
                        uad_bot: String,
                        env: String,
                        tagid: String,
                        tagid_groupe: String,
                        tagid_sous_groupe: String,
                        tagid_intern: String,
                        target_url: String,
                        country: String,
                        region: String,
                        town: String,
                        postalcode: String,
                        name: String,
                        provider: String,
                        provider_family: String,
                        rubrique: String,
                        rubrique_parent: String,
                        rubrique_categorie: String,
                        rubrique_bu: String,
                        rubrique_bu_segment: String,
                        offertype: String,
                        ovm: String,
                        providers: String,
                        allrubrics: String,
                        brand: String,
                        has_epjid: String,
                        onumcli: String,
                        visibilitylevel: String,
                        localbusinesspackage: String,
                        storechains: String,
                        pjrating: String,
                        allappids: String,
                        pjcontent: String,
                        indexedrubricids: String,
                        lastoffertypechange: java.sql.Timestamp,
                        vdeappids: String,
                        tags: String,
                        nb:Long,
                        coefvisibility: Double,
                        cornerappids: String,
                        idabtest: String,
                        idvariant: String,
                        indoorview: String,
                        outdoorview: String,
                        tabsappid: String)
